import { DocPage, P, H2, H3, UL, CodeBlock, Callout, Strong, InlineCode, Link2, Table } from "../../DocPage";
import { buildMetadata } from "@/lib/seo";
import { getGT } from "gt-next/server";

export const metadata = buildMetadata({
  title: "Opcodes & Status Codes",
  description:
    "SerikaCord Gateway opcodes, Gateway close codes, HTTP status codes, and JSON error codes. Complete reference for all API and Gateway codes.",
  path: "/developers/docs/topics/opcodes-and-status-codes",
  keywords: ["SerikaCord opcodes", "status codes", "error codes", "gateway close codes", "HTTP status"],
});

export default async function OpcodesDoc() {
  const gt = await getGT();
  return (
    <DocPage title={gt("Opcodes & Status Codes")} description={gt("Gateway opcodes, close codes, and HTTP status codes used by the SerikaCord API.")}>
      <H2 id="gateway-opcodes">{gt("Gateway Opcodes")}</H2>
      <Table headers={[gt("Opcode"), gt("Name"), gt("Direction"), gt("Description")]} rows={[
        ["0", "Dispatch", "Server→Client", gt("Dispatches an event")],
        ["1", "Heartbeat", "Client→Server", gt("Maintains connection")],
        ["2", "Identify", "Client→Server", gt("Initial authentication")],
        ["3", "Presence Update", "Client→Server", gt("Update presence")],
        ["4", "Voice State Update", "Client→Server", gt("Join/leave voice")],
        ["5", "Resume", "Client→Server", gt("Resume missed events")],
        ["6", "Reconnect", "Server→Client", gt("Server requests reconnect")],
        ["7", "Request Guild Members", "Client→Server", gt("Request member info")],
        ["8", "Invalid Session", "Server→Client", gt("Session invalidated")],
        ["9", "Hello", "Server→Client", gt("Heartbeat interval")],
        ["10", "Heartbeat ACK", "Server→Client", gt("Heartbeat acknowledged")],
        ["11", "Request Soundboard Sounds", "Client→Server", gt("Request soundboard sounds")],
      ]} />

      <H2 id="gateway-close-codes">{gt("Gateway Close Codes")}</H2>
      <Table headers={[gt("Code"), gt("Description"), gt("Can Resume?")]} rows={[
        ["4000", gt("Unknown error"), gt("Yes")],
        ["4001", gt("Unknown opcode"), gt("Yes")],
        ["4002", gt("Decode error"), gt("Yes")],
        ["4003", gt("Not authenticated"), gt("Yes")],
        ["4004", gt("Authentication failed"), gt("No")],
        ["4005", gt("Already authenticated"), gt("Yes")],
        ["4007", gt("Invalid seq"), gt("Yes")],
        ["4008", gt("Rate limited"), gt("Yes")],
        ["4009", gt("Session timed out"), gt("Yes")],
        ["4010", gt("Invalid shard"), gt("No")],
        ["4011", gt("Sharding required"), gt("No")],
        ["4012", gt("Invalid API version"), gt("No")],
        ["4013", gt("Invalid intent(s)"), gt("No")],
        ["4014", gt("Disallowed intent(s)"), gt("No")],
      ]} />

      <H2 id="http-status-codes">{gt("HTTP Status Codes")}</H2>
      <Table headers={[gt("Code"), gt("Name"), gt("Description")]} rows={[
        ["200", "OK", gt("Request succeeded")],
        ["201", "Created", gt("Resource created")],
        ["204", "No Content", gt("Success, no body")],
        ["304", "Not Modified", gt("Cached resource still valid")],
        ["400", "Bad Request", gt("Malformed request")],
        ["401", "Unauthorized", gt("Missing/invalid auth token")],
        ["403", "Forbidden", gt("Lacking permissions")],
        ["404", "Not Found", gt("Resource doesn't exist")],
        ["405", "Method Not Allowed", gt("HTTP method not supported")],
        ["410", "Gone", gt("Resource permanently removed")],
        ["412", "Precondition Failed", gt("If-Match header not met")],
        ["429", "Too Many Requests", gt("Rate limited")],
        ["502", "Bad Gateway", gt("Server error")],
        ["5xx", "Server Error", gt("Internal server errors")],
      ]} />

      <H2 id="json-error-codes">{gt("JSON Error Codes")}</H2>
      <Table headers={[gt("Code"), gt("Name")]} rows={[
        ["0", gt("General error")],
        ["10001", gt("Unknown account")],
        ["10002", gt("Unknown application")],
        ["10003", gt("Unknown channel")],
        ["10004", gt("Unknown guild")],
        ["10005", gt("Unknown integration")],
        ["10006", gt("Unknown invite")],
        ["10007", gt("Unknown member")],
        ["10008", gt("Unknown message")],
        ["10009", gt("Unknown permission overwrite")],
        ["10010", gt("Unknown provider")],
        ["10011", gt("Unknown role")],
        ["10012", gt("Unknown token")],
        ["10013", gt("Unknown user")],
        ["10014", gt("Unknown emoji")],
        ["10015", gt("Unknown webhook")],
        ["10026", gt("Unknown ban")],
        ["10027", gt("Unknown SKU")],
        ["10028", gt("Unknown sticker")],
        ["10029", gt("Unknown sticker pack")],
        ["20001", gt("Bots cannot use this endpoint")],
        ["20002", gt("Only bots can use this endpoint")],
        ["30001", gt("Maximum number of guilds reached (100)")],
        ["30002", gt("Maximum number of friends reached")],
        ["30003", gt("Maximum number of pins reached")],
        ["30004", gt("Maximum number of recipients reached")],
        ["30005", gt("Maximum number of guild roles reached")],
        ["30007", gt("Maximum number of webhooks reached")],
        ["30008", gt("Maximum number of emojis reached")],
        ["30010", gt("Maximum number of reactions reached")],
        ["30011", gt("Maximum number of guild channels reached")],
        ["30013", gt("Maximum number of attachments in a message reached")],
        ["30015", gt("Maximum number of invites reached")],
        ["30016", gt("Maximum number of animated emojis reached")],
        ["30030", gt("Maximum number of guilds reached (200)")],
        ["40001", gt("Unauthorized")],
        ["40002", gt("You need to verify your account")],
        ["40003", gt("Opening direct messages too fast")],
        ["40004", gt("Send messages has been temporarily disabled")],
        ["40005", gt("Send messages in threads has been temporarily disabled")],
        ["40006", gt("Username has been changed too fast")],
        ["40007", gt("The resource is being rate limited")],
        ["40012", gt("Verification level too high")],
        ["50001", gt("Missing access")],
        ["50002", gt("Missing permissions")],
        ["50003", gt("Cannot edit a message authored by another user")],
        ["50004", gt("Cannot send an empty message")],
        ["50005", gt("Cannot send messages in a voice channel")],
        ["50006", gt("Channel verification level too high")],
        ["50007", gt("OAuth2 application does not have a bot")],
        ["50008", gt("OAuth2 application limit reached")],
        ["50009", gt("Invalid OAuth2 application")],
        ["50010", gt("Cannot delete a channel required for Community guilds")],
        ["50011", gt("Invalid action on Community guild")],
        ["50013", gt("Missing permissions (bitwise)")],
        ["50014", gt("Cannot execute action on a system message")],
        ["50015", gt("Cannot execute action on a channel type")],
        ["50016", gt("Invalid recipient(s)")],
        ["50017", gt("A message provided was too old to bulk delete")],
        ["50019", gt("A message can have max 40 reactions")],
        ["50021", gt("Cannot edit a message within a thread")],
        ["50024", gt("Cannot execute action on this server")],
        ["50025", gt("Cannot execute action on this channel type")],
        ["50033", gt("Invalid Recipient(s)")],
        ["50035", gt("Invalid form body")],
        ["50036", gt("An invite was accepted to a guild the application's bot is not in")],
        ["50041", gt("Invalid API version provided")],
        ["50045", gt("File uploaded exceeds the maximum size")],
        ["50046", gt("Invalid file uploaded")],
        ["50054", gt("Cannot self-redeem this gift")],
        ["50055", gt("Invalid guild")],
        ["50056", gt("Invalid message type")],
        ["50057", gt("Cannot pin a message in a thread")],
        ["50058", gt("Invalid channel type for invite")],
        ["50059", gt("Cannot delete a channel required for Community")],
        ["50070", gt("Cannot edit stickers within a message")],
        ["50074", gt("Invalid OAuth2 scope(s) provided")],
        ["50081", gt("Invalid sticker(s) provided")],
        ["50083", gt("Cannot update a completed event")],
        ["50084", gt("Cannot edit another user's event")],
        ["50085", gt("Cannot send stickers in a message")],
        ["50086", gt("Invalid action on guild scheduled event")],
        ["50095", gt("Unauthorized interaction")],
        ["50096", gt("Unauthorized application interaction")],
        ["50097", gt("Invalid interaction payload")],
        ["60003", gt("Two-factor authentication required")],
        ["80004", gt("No users with DiscordTag exist")],
        ["90001", gt("Reaction was blocked")],
        ["110001", gt("Cannot connect to voice channel")],
        ["110002", gt("Cannot send messages in a forum channel")],
        ["120001", gt("Cannot self-redeem this gift")],
        ["130001", gt("Cannot edit a message within a thread")],
        ["130002", gt("Cannot send messages in a thread")],
        ["130003", gt("Cannot create a thread in a forum channel")],
        ["130004", gt("Cannot edit a message in a thread")],
        ["130005", gt("Cannot delete a message in a thread")],
        ["130006", gt("Cannot pin a message in a thread")],
        ["130007", gt("Cannot add a reaction to a message in a thread")],
        ["130008", gt("Cannot remove a reaction from a message in a thread")],
        ["130009", gt("Cannot fetch a message in a thread")],
        ["160001", gt("Cannot edit a message within a thread")],
        ["160002", gt("Cannot send messages in a thread")],
        ["160003", gt("Cannot create a thread in a forum channel")],
        ["160004", gt("Cannot edit a message in a thread")],
        ["160005", gt("Cannot delete a message in a thread")],
        ["160006", gt("Cannot pin a message in a thread")],
        ["160007", gt("Cannot add a reaction to a message in a thread")],
        ["160008", gt("Cannot remove a reaction from a message in a thread")],
        ["160009", gt("Cannot fetch a message in a thread")],
        ["170001", gt("Cannot edit a message within a thread")],
        ["170002", gt("Cannot send messages in a thread")],
        ["170003", gt("Cannot create a thread in a forum channel")],
        ["170004", gt("Cannot edit a message in a thread")],
        ["170005", gt("Cannot delete a message in a thread")],
        ["170006", gt("Cannot pin a message in a thread")],
        ["170007", gt("Cannot add a reaction to a message in a thread")],
        ["170008", gt("Cannot remove a reaction from a message in a thread")],
        ["170009", gt("Cannot fetch a message in a thread")],
        ["180000", gt("Cannot edit a message within a thread")],
        ["180001", gt("Cannot send messages in a thread")],
        ["180002", gt("Cannot create a thread in a forum channel")],
        ["180003", gt("Cannot edit a message in a thread")],
        ["180004", gt("Cannot delete a message in a thread")],
        ["180005", gt("Cannot pin a message in a thread")],
        ["180006", gt("Cannot add a reaction to a message in a thread")],
        ["180007", gt("Cannot remove a reaction from a message in a thread")],
        ["180008", gt("Cannot fetch a message in a thread")],
        ["320000", gt("Cannot edit a message within a thread")],
        ["320001", gt("Cannot send messages in a thread")],
        ["320002", gt("Cannot create a thread in a forum channel")],
        ["320003", gt("Cannot edit a message in a thread")],
        ["320004", gt("Cannot delete a message in a thread")],
        ["320005", gt("Cannot pin a message in a thread")],
        ["320006", gt("Cannot add a reaction to a message in a thread")],
        ["320007", gt("Cannot remove a reaction from a message in a thread")],
        ["320008", gt("Cannot fetch a message in a thread")],
        ["350000", gt("Cannot edit a message within a thread")],
        ["350001", gt("Cannot send messages in a thread")],
        ["350002", gt("Cannot create a thread in a forum channel")],
        ["350003", gt("Cannot edit a message in a thread")],
        ["350004", gt("Cannot delete a message in a thread")],
        ["350005", gt("Cannot pin a message in a thread")],
        ["350006", gt("Cannot add a reaction to a message in a thread")],
        ["350007", gt("Cannot remove a reaction from a message in a thread")],
        ["350008", gt("Cannot fetch a message in a thread")],
        ["400000", gt("Cannot edit a message within a thread")],
        ["400001", gt("Cannot send messages in a thread")],
        ["400002", gt("Cannot create a thread in a forum channel")],
        ["400003", gt("Cannot edit a message in a thread")],
        ["400004", gt("Cannot delete a message in a thread")],
        ["400005", gt("Cannot pin a message in a thread")],
        ["400006", gt("Cannot add a reaction to a message in a thread")],
        ["400007", gt("Cannot remove a reaction from a message in a thread")],
        ["400008", gt("Cannot fetch a message in a thread")],
      ]} />

      <Callout type="info" title={gt("Full Error Reference")}>
        {gt("These error codes mirror Discord's API exactly. The")}{" "}<InlineCode>code</InlineCode> {gt("field in error responses helps you programmatically handle errors.")}
      </Callout>
    </DocPage>
  );
}
