/**
 * Shared chat message types used by both server channels (ChatArea) and DMs.
 */
import type { CallMessageData } from "@/lib/voice/callMessage";
import type { GroupDmEventType } from "@/lib/chat/groupDm";
import type { ThreadSummary } from "@/lib/chat/threads";
import type { PollResultData, PollView } from "@/lib/chat/polls";
import type { ForwardView } from "@/lib/chat/forward";

export interface MessageAuthor {
  id: string;
  username: string;
  displayName: string;
  avatar?: string;
  badges?: string[];
  status?: "online" | "idle" | "dnd" | "offline";
  isPremium?: boolean;
  isOwner?: boolean;
  isSystem?: boolean;
  isBot?: boolean;
  isVerified?: boolean;
  isDiscord?: boolean;
  customization?: {
    profileColor?: string;
    profileAccentColor?: string;
    profileGradient?: string[];
    displayNameStyle?: {
      font?: 'default' | 'serif' | 'mono' | 'rounded' | 'cursive' | 'bold';
      effect?: 'solid' | 'gradient' | 'neon' | 'toon' | 'pop';
      color?: string;
      gradient?: string[];
    };
  } | null;
}

export interface MessageAttachment {
  id: string;
  url: string;
  filename: string;
  contentType: string;
  size?: number;
  spoiler?: boolean;
  /** Flagged by the server's explicit media content filter: blurred until clicked. */
  sensitive?: boolean;
}

export interface MessageReaction {
  emoji: {
    id?: string;
    name: string;
    animated?: boolean;
    url?: string;
  };
  count: number;
  userIds: string[];
}

export interface MessageCustomEmoji {
  id: string;
  name: string;
  animated?: boolean;
  url: string;
}

export interface MessageSticker {
  id: string;
  name: string;
  imageUrl: string;
  serverId?: string;
  serverName?: string;
}

/** Discord-compatible rich embed sent by bots (or generated by link unfurling). */
export interface MessageEmbed {
  title?: string;
  type?: string;
  description?: string;
  url?: string;
  /** Integer color (0xRRGGBB) for the left accent bar. */
  color?: number;
  timestamp?: string;
  footer?: { text?: string; icon_url?: string; iconUrl?: string };
  image?: { url?: string; width?: number; height?: number };
  thumbnail?: { url?: string; width?: number; height?: number };
  video?: { url?: string; width?: number; height?: number };
  provider?: { name?: string; url?: string };
  author?: { name?: string; url?: string; icon_url?: string; iconUrl?: string };
  fields?: { name: string; value: string; inline?: boolean }[];
}

export interface ReferencedMessage {
  id: string;
  content: string;
  author?: {
    id: string;
    username: string;
    displayName: string;
    avatar?: string;
    isBot?: boolean;
    isVerified?: boolean;
    isDiscord?: boolean;
  };
  createdAt?: string;
}

export interface ChatMessage {
  id: string;
  content: string;
  type?: "default" | "reply" | "system" | "call" | "thread_created" | "poll_result" | GroupDmEventType;
  authorId: string;
  author: MessageAuthor;
  channelId: string;
  createdAt: string;
  updatedAt?: string;
  edited?: boolean;
  pinned?: boolean;
  referencedMessageId?: string;
  referencedMessage?: ReferencedMessage;
  attachments?: MessageAttachment[];
  /** Rich embeds (bot-authored, or generated from links). */
  embeds?: MessageEmbed[];
  reactions?: MessageReaction[];
  customEmojis?: MessageCustomEmoji[];
  sticker?: MessageSticker;
  mentionEveryone?: boolean;
  mentionedUserIds?: string[];
  mentionedRoleIds?: string[];
  mentionedChannelIds?: string[];
  /** True while the message is an optimistic send awaiting server confirmation. */
  pending?: boolean;
  /** Ephemeral messages are only visible to the invoking user and are not persisted. */
  ephemeral?: boolean;
  /** Set on a bot's slash-command response: who invoked which command. */
  interaction?: { name: string; user: { id: string; username: string } };
  /** When true, link previews and rich embeds are hidden for this message. */
  suppressEmbeds?: boolean;
  /** Discord message flags (lib/chat/messageFlags): SUPPRESS_NOTIFICATIONS = "@silent". */
  flags?: number;
  /** Set when an incoming channel webhook posted this message (authorId is then the webhook's id). */
  webhookId?: string;
  /** DM call log row (type "call"): who called, when, whether it was answered. */
  call?: CallMessageData | null;
  /** Group DM system row ("X added Y to the group."): who it's about, the new name. */
  groupEvent?: GroupEventData | null;
  /** Thread started from this message, or announced by this "started a thread" row. */
  threadId?: string;
  /** That thread's summary (chip: name, message count, last reply); null once deleted. */
  thread?: ThreadSummary | null;
  /** A poll message: question, answers, live tallies and the viewer's votes. */
  poll?: PollView | null;
  /** A "poll results" row (type "poll_result"): the frozen outcome. */
  pollResult?: PollResultData | null;
  /** A forwarded message: the frozen copy of the original. */
  forward?: ForwardView | null;
}

/** Details of a group DM system row (the actor is the message author). */
export interface GroupEventData {
  kind: GroupDmEventType;
  target?: { id: string; username: string; displayName: string; avatar?: string | null };
  /** channel_name_change: the new name ("" = name removed). */
  name?: string;
}

export interface MessageGroupData<M extends ChatMessage = ChatMessage> {
  author: MessageAuthor;
  timestamp: string;
  messages: M[];
}

/** Builds the emoji identifier the reactions API expects. */
export function reactionEmojiIdentifier(emoji: MessageReaction["emoji"]): string {
  return emoji.id ? `<${emoji.animated ? "a" : ""}:${emoji.name}:${emoji.id}>` : emoji.name;
}
